<?php
// backend/api/reports/registration_slip.php

require_once __DIR__ . '/../db.php';
require_once __DIR__ . '/../../lib/fpdf/fpdf.php';

// Define font path if needed
if(!defined('FPDF_FONTPATH')) define('FPDF_FONTPATH', __DIR__ . '/../../lib/fpdf/font/');

$student_id = (int)($_GET['student_id'] ?? 0);

if ($student_id <= 0) {
    http_response_code(400);
    echo json_encode(['status'=>'error','message'=>'Invalid student ID']);
    exit;
}

// Fetch student + course
$stmt = $pdo->prepare("
    SELECT s.*, c.code AS course_code, c.name AS course_name
    FROM students s
    JOIN courses c ON s.course_id = c.id
    WHERE s.id=:id
");
$stmt->execute([':id' => $student_id]);
$student = $stmt->fetch();

if (!$student) {
    http_response_code(404);
    echo json_encode(['status'=>'error','message'=>'Student not found']);
    exit;
}

// Generate PDF
$pdf = new FPDF();
$pdf->AddPage();

// Header
$pdf->SetFont('Arial','B',16);
$pdf->Cell(0,10,'Registration Confirmation Slip',0,1,'C');
$pdf->Ln(5);

// Registration Info
$pdf->SetFont('Arial','',12);
$pdf->Cell(60,8,'Full Name:',0,0);
$pdf->Cell(0,8,$student['full_name'],0,1);

$pdf->Cell(60,8,'Student ID:',0,0);
$pdf->Cell(0,8,$student['student_id'],0,1);

$pdf->Cell(60,8,'Email:',0,0);
$pdf->Cell(0,8,$student['email'],0,1);

$pdf->Cell(60,8,'Course:',0,0);
$pdf->Cell(0,8,$student['course_code'].' - '.$student['course_name'],0,1);

$pdf->Cell(60,8,'Enrollment Date:',0,0);
$pdf->Cell(0,8,$student['enrollment_date'],0,1);

$pdf->Cell(60,8,'Status:',0,0);
$pdf->Cell(0,8,$student['status'],0,1);

$pdf->Cell(60,8,'Registration Timestamp:',0,0);
$pdf->Cell(0,8,$student['created_at'],0,1);

// Footer
$pdf->Ln(10);
$pdf->SetFont('Arial','I',10);
$pdf->Cell(0,10,'Generated by Student Registration System',0,0,'C');

// Output PDF inline
$pdf->Output('I', "RegistrationSlip_{$student['student_id']}.pdf");
